return {
  -- Copilot is completely disabled
  -- To re-enable, uncomment the configuration below
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   event = "InsertEnter",
  --   opts = {
  --     suggestion = { 
  --       enabled = true,
  --       auto_trigger = true,
  --     },
  --     panel = { 
  --       enabled = true,
  --     },
  --     filetypes = {
  --       ["*"] = true, -- Enable for all file types
  --     },
  --   },
  -- },
}